# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.resize(539, 224)
        self.gridLayoutWidget = QtWidgets.QWidget(OptionsDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 519, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbihb = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.gbihb.setFlat(True)
        self.gbihb.setCheckable(False)
        self.gbihb.setObjectName("gbihb")
        self.layoutWidget = QtWidgets.QWidget(self.gbihb)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 34, 131, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rbunsu = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbunsu.setChecked(True)
        self.rbunsu.setObjectName("rbunsu")
        self.verticalLayout_2.addWidget(self.rbunsu)
        self.rbsvm = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbsvm.setObjectName("rbsvm")
        self.verticalLayout_2.addWidget(self.rbsvm)
        self.rbboth = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbboth.setChecked(False)
        self.rbboth.setObjectName("rbboth")
        self.verticalLayout_2.addWidget(self.rbboth)
        self.verticalLayout.addWidget(self.gbihb)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 5, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gbdata = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.gbdata.setObjectName("gbdata")
        self.layoutWidget_2 = QtWidgets.QWidget(self.gbdata)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 34, 121, 111))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rbbleads = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rbbleads.setChecked(True)
        self.rbbleads.setObjectName("rbbleads")
        self.verticalLayout_3.addWidget(self.rbbleads)
        self.rbleada = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rbleada.setObjectName("rbleada")
        self.verticalLayout_3.addWidget(self.rbleada)
        self.rbleadb = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.rbleadb.setObjectName("rbleadb")
        self.verticalLayout_3.addWidget(self.rbleadb)
        self.horizontalLayout.addWidget(self.gbdata)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 5, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cbrdet = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbrdet.setObjectName("cbrdet")
        self.cbrdet.addItem("")
        self.cbrdet.addItem("")
        self.gridLayout.addWidget(self.cbrdet, 3, 0, 1, 1)
        self.cbfilter = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbfilter.setObjectName("cbfilter")
        self.cbfilter.addItem("")
        self.cbfilter.addItem("")
        self.gridLayout.addWidget(self.cbfilter, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(OptionsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(120, 190, 301, 27))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(OptionsDialog)
        self.buttonBox.accepted.connect(OptionsDialog.accept)
        self.buttonBox.rejected.connect(OptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)

    def retranslateUi(self, OptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        OptionsDialog.setWindowTitle(_translate("OptionsDialog", "Dialog"))
        self.gbihb.setTitle(_translate("OptionsDialog", "IHB Detector"))
        self.rbunsu.setText(_translate("OptionsDialog", "Unsupervised"))
        self.rbsvm.setText(_translate("OptionsDialog", "SVM"))
        self.rbboth.setText(_translate("OptionsDialog", "Both"))
        self.gbdata.setTitle(_translate("OptionsDialog", "Use data from"))
        self.rbbleads.setText(_translate("OptionsDialog", "Both leads"))
        self.rbleada.setText(_translate("OptionsDialog", "Lead A"))
        self.rbleadb.setText(_translate("OptionsDialog", "Lead B"))
        self.label_2.setText(_translate("OptionsDialog", "R Detector:"))
        self.label.setText(_translate("OptionsDialog", "Filter:"))
        self.cbrdet.setItemText(0, _translate("OptionsDialog", "FIRSTDER"))
        self.cbrdet.setItemText(1, _translate("OptionsDialog", "PARABOLIC"))
        self.cbfilter.setItemText(0, _translate("OptionsDialog", "IIR"))
        self.cbfilter.setItemText(1, _translate("OptionsDialog", "FIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptionsDialog = QtWidgets.QDialog()
    ui = Ui_OptionsDialog()
    ui.setupUi(OptionsDialog)
    OptionsDialog.show()
    sys.exit(app.exec_())

