# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionsform.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptionsForm(object):
    def setupUi(self, OptionsForm):
        OptionsForm.setObjectName("OptionsForm")
        OptionsForm.resize(475, 222)
        self.gridLayoutWidget = QtWidgets.QWidget(OptionsForm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cbrdet = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbrdet.setObjectName("cbrdet")
        self.cbrdet.addItem("")
        self.cbrdet.addItem("")
        self.gridLayout.addWidget(self.cbrdet, 3, 0, 1, 1)
        self.cbfilter = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbfilter.setObjectName("cbfilter")
        self.cbfilter.addItem("")
        self.cbfilter.addItem("")
        self.gridLayout.addWidget(self.cbfilter, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbihb = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.gbihb.setFlat(True)
        self.gbihb.setCheckable(False)
        self.gbihb.setObjectName("gbihb")
        self.splitter = QtWidgets.QSplitter(self.gbihb)
        self.splitter.setGeometry(QtCore.QRect(16, 40, 121, 101))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.rbunsu = QtWidgets.QRadioButton(self.splitter)
        self.rbunsu.setObjectName("rbunsu")
        self.rbsvm = QtWidgets.QRadioButton(self.splitter)
        self.rbsvm.setObjectName("rbsvm")
        self.rbboth = QtWidgets.QRadioButton(self.splitter)
        self.rbboth.setObjectName("rbboth")
        self.verticalLayout.addWidget(self.gbihb)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 5, 1)
        self.pbcancel = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pbcancel.setObjectName("pbcancel")
        self.gridLayout.addWidget(self.pbcancel, 5, 2, 1, 1)
        self.pbdef = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pbdef.setObjectName("pbdef")
        self.gridLayout.addWidget(self.pbdef, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gbdata = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.gbdata.setObjectName("gbdata")
        self.splitter_2 = QtWidgets.QSplitter(self.gbdata)
        self.splitter_2.setGeometry(QtCore.QRect(20, 40, 111, 101))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.rbbleads = QtWidgets.QRadioButton(self.splitter_2)
        self.rbbleads.setObjectName("rbbleads")
        self.rbleada = QtWidgets.QRadioButton(self.splitter_2)
        self.rbleada.setObjectName("rbleada")
        self.rbleadb = QtWidgets.QRadioButton(self.splitter_2)
        self.rbleadb.setObjectName("rbleadb")
        self.horizontalLayout.addWidget(self.gbdata)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 5, 1)
        self.pbok = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pbok.setObjectName("pbok")
        self.gridLayout.addWidget(self.pbok, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(OptionsForm)
        QtCore.QMetaObject.connectSlotsByName(OptionsForm)
        OptionsForm.setTabOrder(self.cbfilter, self.cbrdet)
        OptionsForm.setTabOrder(self.cbrdet, self.rbunsu)
        OptionsForm.setTabOrder(self.rbunsu, self.rbsvm)
        OptionsForm.setTabOrder(self.rbsvm, self.rbboth)
        OptionsForm.setTabOrder(self.rbboth, self.rbbleads)
        OptionsForm.setTabOrder(self.rbbleads, self.rbleada)
        OptionsForm.setTabOrder(self.rbleada, self.rbleadb)
        OptionsForm.setTabOrder(self.rbleadb, self.pbok)
        OptionsForm.setTabOrder(self.pbok, self.pbdef)
        OptionsForm.setTabOrder(self.pbdef, self.pbcancel)

    def retranslateUi(self, OptionsForm):
        _translate = QtCore.QCoreApplication.translate
        OptionsForm.setWindowTitle(_translate("OptionsForm", "Options"))
        self.cbrdet.setItemText(0, _translate("OptionsForm", "FIRSTDER"))
        self.cbrdet.setItemText(1, _translate("OptionsForm", "PARABOLIC"))
        self.cbfilter.setItemText(0, _translate("OptionsForm", "IIR"))
        self.cbfilter.setItemText(1, _translate("OptionsForm", "FIR"))
        self.gbihb.setTitle(_translate("OptionsForm", "IHB Detector"))
        self.rbunsu.setText(_translate("OptionsForm", "Unsupervised"))
        self.rbsvm.setText(_translate("OptionsForm", "SVM"))
        self.rbboth.setText(_translate("OptionsForm", "Both"))
        self.pbcancel.setText(_translate("OptionsForm", "Cancel"))
        self.pbdef.setText(_translate("OptionsForm", "Default"))
        self.label_2.setText(_translate("OptionsForm", "R Detector:"))
        self.gbdata.setTitle(_translate("OptionsForm", "Use data from"))
        self.rbbleads.setText(_translate("OptionsForm", "Both leads"))
        self.rbleada.setText(_translate("OptionsForm", "Lead A"))
        self.rbleadb.setText(_translate("OptionsForm", "Lead B"))
        self.pbok.setText(_translate("OptionsForm", "OK"))
        self.label.setText(_translate("OptionsForm", "Filter:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptionsForm = QtWidgets.QWidget()
    ui = Ui_OptionsForm()
    ui.setupUi(OptionsForm)
    OptionsForm.show()
    sys.exit(app.exec_())

