# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settwin.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/images/logo-PyECG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(242, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.sett_pb_default = QtWidgets.QPushButton(Dialog)
        self.sett_pb_default.setObjectName("sett_pb_default")
        self.gridLayout.addWidget(self.sett_pb_default, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 3, 1, 1)
        self.sett_tab_widget = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sett_tab_widget.setFont(font)
        self.sett_tab_widget.setTabPosition(QtWidgets.QTabWidget.West)
        self.sett_tab_widget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.sett_tab_widget.setIconSize(QtCore.QSize(24, 24))
        self.sett_tab_widget.setElideMode(QtCore.Qt.ElideMiddle)
        self.sett_tab_widget.setTabBarAutoHide(False)
        self.sett_tab_widget.setObjectName("sett_tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sett_combobox_1 = QtWidgets.QComboBox(self.groupBox)
        self.sett_combobox_1.setObjectName("sett_combobox_1")
        self.sett_combobox_1.addItem("")
        self.sett_combobox_1.addItem("")
        self.sett_combobox_1.addItem("")
        self.gridLayout_3.addWidget(self.sett_combobox_1, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sett_combobox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.sett_combobox_2.setObjectName("sett_combobox_2")
        self.gridLayout_4.addWidget(self.sett_combobox_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.sett_tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 738, 527))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.sett_tab_widget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 738, 527))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.sett_tab_widget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.sett_db_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.sett_db_lineEdit.setDragEnabled(True)
        self.sett_db_lineEdit.setObjectName("sett_db_lineEdit")
        self.gridLayout_8.addWidget(self.sett_db_lineEdit, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 0, 1, 1, 1)
        self.sett_db__open_button = QtWidgets.QPushButton(self.groupBox_3)
        self.sett_db__open_button.setObjectName("sett_db__open_button")
        self.gridLayout_8.addWidget(self.sett_db__open_button, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 0, 3, 1, 1)
        self.sett_db__new_button = QtWidgets.QPushButton(self.groupBox_3)
        self.sett_db__new_button.setObjectName("sett_db__new_button")
        self.gridLayout_8.addWidget(self.sett_db__new_button, 0, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 0, 5, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 320, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 1, 0, 1, 1)
        self.sett_tab_widget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.sett_tab_widget, 0, 0, 1, 4)

        self.retranslateUi(Dialog)
        self.sett_tab_widget.setCurrentIndex(3)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Configuración"))
        self.sett_pb_default.setText(_translate("Dialog", "Por Defecto"))
        self.groupBox.setTitle(_translate("Dialog", "Idioma"))
        self.sett_combobox_1.setItemText(0, _translate("Dialog", "Spanish(ES)"))
        self.sett_combobox_1.setItemText(1, _translate("Dialog", "English(EN)"))
        self.sett_combobox_1.setItemText(2, _translate("Dialog", "Dutch(NL)"))
        self.groupBox_2.setTitle(_translate("Dialog", "Estilo Visual"))
        self.sett_tab_widget.setTabText(self.sett_tab_widget.indexOf(self.tab), _translate("Dialog", "Interfaz"))
        self.sett_tab_widget.setTabText(self.sett_tab_widget.indexOf(self.tab_2), _translate("Dialog", "Programa"))
        self.sett_tab_widget.setTabText(self.sett_tab_widget.indexOf(self.tab_3), _translate("Dialog", "General"))
        self.groupBox_3.setTitle(_translate("Dialog", "Ubicación de la Base de datos"))
        self.sett_db__open_button.setText(_translate("Dialog", "Abrir"))
        self.sett_db__new_button.setText(_translate("Dialog", "Nueva BD"))
        self.sett_tab_widget.setTabText(self.sett_tab_widget.indexOf(self.tab_4), _translate("Dialog", "Base de Datos"))


# import resc_rc
