# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windp.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 568)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/images/logo-PyECG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 0))
        self.toolBox.setObjectName("toolBox")
        self.tlpage_1 = QtWidgets.QWidget()
        self.tlpage_1.setGeometry(QtCore.QRect(0, 0, 200, 367))
        self.tlpage_1.setObjectName("tlpage_1")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tlpage_1)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.scrollArea_preproc = QtWidgets.QScrollArea(self.tlpage_1)
        self.scrollArea_preproc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_preproc.setWidgetResizable(True)
        self.scrollArea_preproc.setObjectName("scrollArea_preproc")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 182, 270))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pproc_filt = QtWidgets.QComboBox(self.groupBox_5)
        self.pproc_filt.setGeometry(QtCore.QRect(8, 30, 151, 22))
        self.pproc_filt.setObjectName("pproc_filt")
        self.pproc_filt.addItem("")
        self.pproc_filt.addItem("")
        self.pproc_filt.addItem("")
        self.pproc_filt.addItem("")
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_30.setObjectName("gridLayout_30")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem1, 0, 2, 1, 1)
        self.lost_bt = QtWidgets.QPushButton(self.groupBox_6)
        self.lost_bt.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/mono-font-awesome/images/icons/mono-font-awesome/png/eye-open.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/mono-font-awesome/images/icons/mono-font-awesome/png/eye-open.png"),
                        QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.lost_bt.setIcon(icon1)
        self.lost_bt.setCheckable(True)
        self.lost_bt.setFlat(True)
        self.lost_bt.setObjectName("lost_bt")
        self.gridLayout_30.addWidget(self.lost_bt, 1, 2, 1, 1)
        self.pproc_lostl = QtWidgets.QComboBox(self.groupBox_6)
        self.pproc_lostl.setObjectName("pproc_lostl")
        self.pproc_lostl.addItem("")
        self.pproc_lostl.addItem("")
        self.gridLayout_30.addWidget(self.pproc_lostl, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_31.addWidget(self.comboBox, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.scrollArea_preproc.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_21.addWidget(self.scrollArea_preproc, 0, 0, 1, 1)
        self.gBox_channel = QtWidgets.QGroupBox(self.tlpage_1)
        self.gBox_channel.setFlat(True)
        self.gBox_channel.setObjectName("gBox_channel")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.gBox_channel)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.radioButton = QtWidgets.QRadioButton(self.gBox_channel)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_32.addWidget(self.radioButton, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_32.addItem(spacerItem2, 0, 1, 2, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gBox_channel)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_32.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.gridLayout_21.addWidget(self.gBox_channel, 1, 0, 1, 1)
        self.toolBox.addItem(self.tlpage_1, "")
        self.tlpage_2 = QtWidgets.QWidget()
        self.tlpage_2.setGeometry(QtCore.QRect(0, 0, 200, 367))
        self.tlpage_2.setObjectName("tlpage_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tlpage_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tlpage_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.cmbox_hrv1 = QtWidgets.QComboBox(self.tlpage_2)
        self.cmbox_hrv1.setMinimumContentsLength(0)
        self.cmbox_hrv1.setObjectName("cmbox_hrv1")
        self.cmbox_hrv1.addItem("")
        self.cmbox_hrv1.addItem("")
        self.cmbox_hrv1.addItem("")
        self.cmbox_hrv1.addItem("")
        self.verticalLayout_2.addWidget(self.cmbox_hrv1)
        self.scrollArea_hrv = QtWidgets.QScrollArea(self.tlpage_2)
        self.scrollArea_hrv.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_hrv.setWidgetResizable(True)
        self.scrollArea_hrv.setObjectName("scrollArea_hrv")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 182, 304))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_35.addWidget(self.comboBox_6, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_4.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_10.setFlat(True)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_4.addWidget(self.groupBox_10)
        self.scrollArea_hrv.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_hrv)
        self.toolBox.addItem(self.tlpage_2, "")
        self.tlpage_3 = QtWidgets.QWidget()
        self.tlpage_3.setGeometry(QtCore.QRect(0, 0, 200, 367))
        self.tlpage_3.setObjectName("tlpage_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tlpage_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_qtv = QtWidgets.QScrollArea(self.tlpage_3)
        self.scrollArea_qtv.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_qtv.setWidgetResizable(True)
        self.scrollArea_qtv.setObjectName("scrollArea_qtv")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 182, 349))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_11 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_11.setFlat(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_5)
        self.verticalLayout_5.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_12.setFlat(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_5.addWidget(self.groupBox_12)
        self.groupBox_13 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_13.setTitle("")
        self.groupBox_13.setFlat(True)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_5.addWidget(self.groupBox_13)
        self.scrollArea_qtv.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.addWidget(self.scrollArea_qtv)
        self.toolBox.addItem(self.tlpage_3, "")
        self.tlpage_4 = QtWidgets.QWidget()
        self.tlpage_4.setGeometry(QtCore.QRect(0, 0, 203, 367))
        self.tlpage_4.setObjectName("tlpage_4")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tlpage_4)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.scrollArea_qtd = QtWidgets.QScrollArea(self.tlpage_4)
        self.scrollArea_qtd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_qtd.setWidgetResizable(True)
        self.scrollArea_qtd.setObjectName("scrollArea_qtd")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 187, 332))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_14 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_14.setFlat(True)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_14)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_8.addWidget(self.comboBox_3)
        self.verticalLayout_6.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_15.setFlat(True)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_15)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_33.addWidget(self.comboBox_4, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_15)
        self.groupBox_16 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_16.setFlat(True)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_16)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_34.addWidget(self.comboBox_2, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_16)
        self.scrollArea_qtd.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_22.addWidget(self.scrollArea_qtd, 0, 0, 1, 1)
        self.toolBox.addItem(self.tlpage_4, "")
        self.horizontalLayout.addWidget(self.toolBox)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_plot)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tab_reg_basewdg = QtWidgets.QWidget(self.tab_plot)
        self.tab_reg_basewdg.setMinimumSize(QtCore.QSize(0, 24))
        self.tab_reg_basewdg.setObjectName("tab_reg_basewdg")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_reg_basewdg)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_reg_basewdg)
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_reg_basewdg)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_reg_basewdg)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_3.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_reg_basewdg)
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_reg_basewdg)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton = QtWidgets.QPushButton(self.tab_reg_basewdg)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addWidget(self.tab_reg_basewdg, 2, 0, 1, 1)
        self.graphicsView_1 = PlotWidget(self.tab_plot)
        self.graphicsView_1.setMinimumSize(QtCore.QSize(0, 40))
        self.graphicsView_1.setMouseTracking(True)
        self.graphicsView_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.graphicsView_1.setObjectName("graphicsView_1")
        self.gridLayout.addWidget(self.graphicsView_1, 1, 0, 1, 1)
        self.graphicsView = PlotWidget(self.tab_plot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 40))
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gBox_lost_beat = QtWidgets.QGroupBox(self.tab_plot)
        self.gBox_lost_beat.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBox_lost_beat.sizePolicy().hasHeightForWidth())
        self.gBox_lost_beat.setSizePolicy(sizePolicy)
        self.gBox_lost_beat.setMaximumSize(QtCore.QSize(160, 16777215))
        self.gBox_lost_beat.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.gBox_lost_beat.setFlat(True)
        self.gBox_lost_beat.setObjectName("gBox_lost_beat")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.gBox_lost_beat)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.listwdg_lost_beat = QtWidgets.QListWidget(self.gBox_lost_beat)
        self.listwdg_lost_beat.setEnabled(False)
        self.listwdg_lost_beat.setObjectName("listwdg_lost_beat")
        self.gridLayout_23.addWidget(self.listwdg_lost_beat, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gBox_lost_beat, 0, 1, 2, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_plot, "")
        self.tab_hrv = QtWidgets.QWidget()
        self.tab_hrv.setObjectName("tab_hrv")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_hrv)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stack_hrv = QtWidgets.QStackedWidget(self.tab_hrv)
        self.stack_hrv.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.stack_hrv.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stack_hrv.setLineWidth(2)
        self.stack_hrv.setMidLineWidth(23)
        self.stack_hrv.setObjectName("stack_hrv")
        self.spage_1 = QtWidgets.QWidget()
        self.spage_1.setObjectName("spage_1")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.spage_1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox = QtWidgets.QGroupBox(self.spage_1)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.graphicsView_2 = GraphicsLayoutWidget(self.groupBox)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_20.addWidget(self.graphicsView_2, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox, 0, 0, 1, 1)
        self.stack_hrv.addWidget(self.spage_1)
        self.spage_2 = QtWidgets.QWidget()
        self.spage_2.setObjectName("spage_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.spage_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_2 = QtWidgets.QGroupBox(self.spage_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.graphicsView_3 = GraphicsLayoutWidget(self.groupBox_2)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayout_19.addWidget(self.graphicsView_3, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.stack_hrv.addWidget(self.spage_2)
        self.spage_3 = QtWidgets.QWidget()
        self.spage_3.setObjectName("spage_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.spage_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_3 = QtWidgets.QGroupBox(self.spage_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.graphicsView_4 = GraphicsLayoutWidget(self.groupBox_3)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout_18.addWidget(self.graphicsView_4, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.stack_hrv.addWidget(self.spage_3)
        self.spage_4 = QtWidgets.QWidget()
        self.spage_4.setObjectName("spage_4")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.spage_4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox_4 = QtWidgets.QGroupBox(self.spage_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_17.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.stack_hrv.addWidget(self.spage_4)
        self.gridLayout_3.addWidget(self.stack_hrv, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_hrv, "")
        self.tab_qtvi = QtWidgets.QWidget()
        self.tab_qtvi.setObjectName("tab_qtvi")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_qtvi)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.graphicsView_5 = PlotWidget(self.tab_qtvi)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.gridLayout_4.addWidget(self.graphicsView_5, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_qtvi, "")
        self.tab_qtrr = QtWidgets.QWidget()
        self.tab_qtrr.setObjectName("tab_qtrr")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_qtrr)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.graphicsView_6 = PlotWidget(self.tab_qtrr)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.gridLayout_5.addWidget(self.graphicsView_6, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_qtrr, "")
        self.tab_metad = QtWidgets.QWidget()
        self.tab_metad.setObjectName("tab_metad")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_metad)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_metad)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 706, 427))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.le_fname = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.le_fname.setObjectName("le_fname")
        self.gridLayout_24.addWidget(self.le_fname, 2, 1, 1, 1)
        self.lb_name = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.lb_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_name.setObjectName("lb_name")
        self.gridLayout_24.addWidget(self.lb_name, 1, 0, 1, 1)
        self.le_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.le_name.setInputMask("")
        self.le_name.setObjectName("le_name")
        self.gridLayout_24.addWidget(self.le_name, 1, 1, 1, 1)
        self.lb_ci_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.lb_ci_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_ci_3.setObjectName("lb_ci_3")
        self.gridLayout_24.addWidget(self.lb_ci_3, 1, 3, 1, 1)
        self.le_age = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.le_age.setAcceptDrops(False)
        self.le_age.setToolTip("")
        self.le_age.setInputMask("")
        self.le_age.setText("")
        self.le_age.setMaxLength(32767)
        self.le_age.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.le_age.setPlaceholderText("")
        self.le_age.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.le_age.setObjectName("le_age")
        self.gridLayout_24.addWidget(self.le_age, 1, 5, 1, 1)
        self.rb_m = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_6)
        self.rb_m.setChecked(True)
        self.rb_m.setObjectName("rb_m")
        self.gridLayout_24.addWidget(self.rb_m, 2, 5, 1, 1)
        self.pbt_update = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.pbt_update.setObjectName("pbt_update")
        self.gridLayout_24.addWidget(self.pbt_update, 6, 6, 1, 1)
        self.rb_f = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_6)
        self.rb_f.setObjectName("rb_f")
        self.gridLayout_24.addWidget(self.rb_f, 3, 5, 1, 1)
        self.le_id_clinic = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.le_id_clinic.setAcceptDrops(False)
        self.le_id_clinic.setToolTip("")
        self.le_id_clinic.setInputMask("")
        self.le_id_clinic.setMaxLength(32767)
        self.le_id_clinic.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.le_id_clinic.setPlaceholderText("")
        self.le_id_clinic.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.le_id_clinic.setObjectName("le_id_clinic")
        self.gridLayout_24.addWidget(self.le_id_clinic, 0, 5, 1, 1)
        self.lb_sname = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.lb_sname.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lb_sname.setObjectName("lb_sname")
        self.gridLayout_24.addWidget(self.lb_sname, 3, 0, 1, 1)
        self.le_sname = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.le_sname.setObjectName("le_sname")
        self.gridLayout_24.addWidget(self.le_sname, 3, 1, 1, 1)
        self.lb_fname = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.lb_fname.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_fname.setObjectName("lb_fname")
        self.gridLayout_24.addWidget(self.lb_fname, 2, 0, 1, 1)
        self.lb_id_clinic = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.lb_id_clinic.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lb_id_clinic.setObjectName("lb_id_clinic")
        self.gridLayout_24.addWidget(self.lb_id_clinic, 0, 3, 1, 1)
        self.lb_id = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.lb_id.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lb_id.setObjectName("lb_id")
        self.gridLayout_24.addWidget(self.lb_id, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_24.addItem(spacerItem4, 6, 2, 1, 1)
        self.lb_ci_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.lb_ci_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_ci_4.setObjectName("lb_ci_4")
        self.gridLayout_24.addWidget(self.lb_ci_4, 2, 3, 1, 1)
        self.lb_addr = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.lb_addr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_addr.setObjectName("lb_addr")
        self.gridLayout_24.addWidget(self.lb_addr, 5, 0, 1, 1)
        self.le_id = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.le_id.setAcceptDrops(False)
        self.le_id.setToolTip("")
        self.le_id.setInputMask("")
        self.le_id.setText("")
        self.le_id.setMaxLength(11)
        self.le_id.setFrame(True)
        self.le_id.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.le_id.setPlaceholderText("")
        self.le_id.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.le_id.setClearButtonEnabled(True)
        self.le_id.setObjectName("le_id")
        self.gridLayout_24.addWidget(self.le_id, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem5, 6, 3, 1, 3)
        self.dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents_6)
        self.dateEdit.setProperty("showGroupSeparator", True)
        self.dateEdit.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.dateEdit.setMinimumDate(QtCore.QDate(1800, 9, 14))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_24.addWidget(self.dateEdit, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_24.addWidget(self.label_3, 4, 0, 1, 1)
        self.texed_address = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_6)
        self.texed_address.setPlainText("")
        self.texed_address.setObjectName("texed_address")
        self.gridLayout_24.addWidget(self.texed_address, 5, 1, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_6.addWidget(self.scrollArea_5, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_metad, "")
        self.tab_notes = QtWidgets.QWidget()
        self.tab_notes.setEnabled(True)
        self.tab_notes.setObjectName("tab_notes")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_notes)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lsw_com = QtWidgets.QListWidget(self.tab_notes)
        self.lsw_com.setEnabled(False)
        self.lsw_com.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lsw_com.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lsw_com.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lsw_com.setAlternatingRowColors(True)
        self.lsw_com.setResizeMode(QtWidgets.QListView.Fixed)
        self.lsw_com.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.lsw_com.setObjectName("lsw_com")
        self.gridLayout_7.addWidget(self.lsw_com, 0, 0, 5, 1)
        self.btn_com_add = QtWidgets.QPushButton(self.tab_notes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_com_add.sizePolicy().hasHeightForWidth())
        self.btn_com_add.setSizePolicy(sizePolicy)
        self.btn_com_add.setObjectName("btn_com_add")
        self.gridLayout_7.addWidget(self.btn_com_add, 0, 1, 1, 1)
        self.stack_widg_comment = QtWidgets.QStackedWidget(self.tab_notes)
        self.stack_widg_comment.setObjectName("stack_widg_comment")
        self.skw_comm_pg1 = QtWidgets.QWidget()
        self.skw_comm_pg1.setObjectName("skw_comm_pg1")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.skw_comm_pg1)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gb_comm_pg1 = QtWidgets.QGroupBox(self.skw_comm_pg1)
        self.gb_comm_pg1.setObjectName("gb_comm_pg1")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gb_comm_pg1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.txed_comm_pg1 = QtWidgets.QTextEdit(self.gb_comm_pg1)
        self.txed_comm_pg1.setObjectName("txed_comm_pg1")
        self.gridLayout_13.addWidget(self.txed_comm_pg1, 0, 0, 1, 1)
        self.gridLayout_28.addWidget(self.gb_comm_pg1, 0, 0, 1, 1)
        self.stack_widg_comment.addWidget(self.skw_comm_pg1)
        self.skw_comm_pg2 = QtWidgets.QWidget()
        self.skw_comm_pg2.setObjectName("skw_comm_pg2")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.skw_comm_pg2)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.gb_comm_pg2 = QtWidgets.QGroupBox(self.skw_comm_pg2)
        self.gb_comm_pg2.setObjectName("gb_comm_pg2")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.gb_comm_pg2)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.txed_comm_pg2 = QtWidgets.QTextEdit(self.gb_comm_pg2)
        self.txed_comm_pg2.setObjectName("txed_comm_pg2")
        self.gridLayout_26.addWidget(self.txed_comm_pg2, 0, 0, 1, 1)
        self.gridLayout_27.addWidget(self.gb_comm_pg2, 0, 0, 1, 1)
        self.stack_widg_comment.addWidget(self.skw_comm_pg2)
        self.skw_comm_pg3 = QtWidgets.QWidget()
        self.skw_comm_pg3.setObjectName("skw_comm_pg3")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.skw_comm_pg3)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.gb_comm_pg3 = QtWidgets.QGroupBox(self.skw_comm_pg3)
        self.gb_comm_pg3.setObjectName("gb_comm_pg3")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.gb_comm_pg3)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.txed_comm_pg3 = QtWidgets.QTextEdit(self.gb_comm_pg3)
        self.txed_comm_pg3.setObjectName("txed_comm_pg3")
        self.gridLayout_25.addWidget(self.txed_comm_pg3, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.gb_comm_pg3, 0, 0, 1, 1)
        self.stack_widg_comment.addWidget(self.skw_comm_pg3)
        self.gridLayout_7.addWidget(self.stack_widg_comment, 0, 2, 5, 1)
        self.btn_com_remove = QtWidgets.QPushButton(self.tab_notes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_com_remove.sizePolicy().hasHeightForWidth())
        self.btn_com_remove.setSizePolicy(sizePolicy)
        self.btn_com_remove.setObjectName("btn_com_remove")
        self.gridLayout_7.addWidget(self.btn_com_remove, 1, 1, 1, 1)
        self.btn_com_info = QtWidgets.QPushButton(self.tab_notes)
        self.btn_com_info.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_com_info.sizePolicy().hasHeightForWidth())
        self.btn_com_info.setSizePolicy(sizePolicy)
        self.btn_com_info.setObjectName("btn_com_info")
        self.gridLayout_7.addWidget(self.btn_com_info, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 281, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem7, 4, 1, 1, 1)
        self.cmbox_comments = QtWidgets.QComboBox(self.tab_notes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbox_comments.sizePolicy().hasHeightForWidth())
        self.cmbox_comments.setSizePolicy(sizePolicy)
        self.cmbox_comments.setMinimumSize(QtCore.QSize(200, 0))
        self.cmbox_comments.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbox_comments.setObjectName("cmbox_comments")
        self.cmbox_comments.addItem("")
        self.cmbox_comments.addItem("")
        self.cmbox_comments.addItem("")
        self.gridLayout_7.addWidget(self.cmbox_comments, 5, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(501, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem8, 5, 1, 1, 2)
        self.tabWidget.addTab(self.tab_notes, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.open_study = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/mono-font-awesome/images/icons/mono-font-awesome/png/open-folder.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_study.setIcon(icon2)
        self.open_study.setObjectName("open_study")
        self.horizontalLayout_2.addWidget(self.open_study)
        self.save_study = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/icons/mono-font-awesome/images/icons/mono-font-awesome/png/save-file-option.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_study.setIcon(icon3)
        self.save_study.setObjectName("save_study")
        self.horizontalLayout_2.addWidget(self.save_study)
        self.new_study = QtWidgets.QPushButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/mono-font-awesome/images/icons/mono-font-awesome/png/file.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_study.setIcon(icon4)
        self.new_study.setObjectName("new_study")
        self.horizontalLayout_2.addWidget(self.new_study)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.importbtn = QtWidgets.QPushButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/mono-arrows/images/icons/mono-arrows/png/068-import-1.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importbtn.setIcon(icon5)
        self.importbtn.setObjectName("importbtn")
        self.horizontalLayout_2.addWidget(self.importbtn)
        self.exportbtn = QtWidgets.QPushButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/mono-arrows/images/icons/mono-arrows/png/071-export-1.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportbtn.setIcon(icon6)
        self.exportbtn.setObjectName("exportbtn")
        self.horizontalLayout_2.addWidget(self.exportbtn)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.tunebtn = QtWidgets.QPushButton(self.centralwidget)
        self.tunebtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/color-sett/images/icons/color-sett/png/001-wrench-3.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tunebtn.setIcon(icon7)
        self.tunebtn.setObjectName("tunebtn")
        self.horizontalLayout_2.addWidget(self.tunebtn)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.confbtn = QtWidgets.QToolButton(self.centralwidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/color-sett/images/icons/color-sett/png/025-setting-1.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.confbtn.setIcon(icon8)
        self.confbtn.setObjectName("confbtn")
        self.horizontalLayout_2.addWidget(self.confbtn)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setGeometry(QtCore.QRect(185, 139, 150, 200))
        self.menuArchivo.setMinimumSize(QtCore.QSize(0, 0))
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuVista = QtWidgets.QMenu(self.menubar)
        self.menuVista.setObjectName("menuVista")
        self.menuConfiguracion = QtWidgets.QMenu(self.menubar)
        self.menuConfiguracion.setObjectName("menuConfiguracion")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_study = QtWidgets.QAction(MainWindow)
        self.action_open_study.setObjectName("action_open_study")
        self.action_new_study = QtWidgets.QAction(MainWindow)
        self.action_new_study.setObjectName("action_new_study")
        self.action_save_study = QtWidgets.QAction(MainWindow)
        self.action_save_study.setObjectName("action_save_study")
        self.action_import_record = QtWidgets.QAction(MainWindow)
        self.action_import_record.setObjectName("action_import_record")
        self.action_export_record = QtWidgets.QAction(MainWindow)
        self.action_export_record.setObjectName("action_export_record")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_general_config = QtWidgets.QAction(MainWindow)
        self.action_general_config.setObjectName("action_general_config")
        self.action_user_guide = QtWidgets.QAction(MainWindow)
        self.action_user_guide.setObjectName("action_user_guide")
        self.action_user_manual = QtWidgets.QAction(MainWindow)
        self.action_user_manual.setObjectName("action_user_manual")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_toolbox_view = QtWidgets.QAction(MainWindow)
        self.action_toolbox_view.setCheckable(True)
        self.action_toolbox_view.setChecked(True)
        self.action_toolbox_view.setObjectName("action_toolbox_view")
        self.action_lostbeat_view = QtWidgets.QAction(MainWindow)
        self.action_lostbeat_view.setCheckable(True)
        self.action_lostbeat_view.setChecked(False)
        self.action_lostbeat_view.setObjectName("action_lostbeat_view")
        self.menuArchivo.addAction(self.action_open_study)
        self.menuArchivo.addAction(self.action_new_study)
        self.menuArchivo.addAction(self.action_save_study)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.action_import_record)
        self.menuArchivo.addAction(self.action_export_record)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.action_Exit)
        self.menuVista.addAction(self.action_toolbox_view)
        self.menuVista.addSeparator()
        self.menuVista.addAction(self.action_lostbeat_view)
        self.menuConfiguracion.addAction(self.action_general_config)
        self.menuAyuda.addAction(self.action_user_guide)
        self.menuAyuda.addAction(self.action_user_manual)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.action_About)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuVista.menuAction())
        self.menubar.addAction(self.menuConfiguracion.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.lb_name.setBuddy(self.le_name)
        self.lb_ci_3.setBuddy(self.le_age)
        self.lb_sname.setBuddy(self.le_sname)
        self.lb_fname.setBuddy(self.le_fname)
        self.lb_id_clinic.setBuddy(self.le_id_clinic)
        self.lb_id.setBuddy(self.le_id)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.cmbox_hrv1.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.stack_hrv.setCurrentIndex(2)
        self.action_toolbox_view.toggled['bool'].connect(self.toolBox.setVisible)
        self.action_lostbeat_view.toggled['bool'].connect(self.gBox_lost_beat.setVisible)
        self.tunebtn.toggled['bool'].connect(self.toolBox.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyECG"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Filtro"))
        self.pproc_filt.setItemText(0, _translate("MainWindow", "Tipo-IIR(50Hz)"))
        self.pproc_filt.setItemText(1, _translate("MainWindow", "Tipo-FIR(50Hz)"))
        self.pproc_filt.setItemText(2, _translate("MainWindow", "Tipo-IIR(60Hz)"))
        self.pproc_filt.setItemText(3, _translate("MainWindow", "Tipo-FIR(60Hz)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Anotación"))
        self.pproc_lostl.setItemText(0, _translate("MainWindow", "Interna"))
        self.pproc_lostl.setItemText(1, _translate("MainWindow", "Externa"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Algoritmo de Detección"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Ajuste parabólico"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Segunda Derivada"))
        self.gBox_channel.setTitle(_translate("MainWindow", "Seleccionar Canal"))
        self.radioButton.setText(_translate("MainWindow", "Canal A"))
        self.radioButton_2.setText(_translate("MainWindow", "Canal B"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tlpage_1), _translate("MainWindow", "Procesamiento"))
        self.label.setText(_translate("MainWindow", "Vista HRV"))
        self.cmbox_hrv1.setItemText(0, _translate("MainWindow", "Análisis espacial HRV"))
        self.cmbox_hrv1.setItemText(1, _translate("MainWindow", "Análisis frecuencial"))
        self.cmbox_hrv1.setItemText(2, _translate("MainWindow", "Análisis no lineal"))
        self.cmbox_hrv1.setItemText(3, _translate("MainWindow", "HRV Resumen"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Tamaño de ventana"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "5 minutos"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "15 minutos"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "30 minutos"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "60 minutos"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "3 horas"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "6 horas"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "12 horas"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "24 horas"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Análisis espectral"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Análisis no lineal"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tlpage_2), _translate("MainWindow", "Análisis HRV"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Tamaño de ventana"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "5 minutos"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "15 minutos"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "30 minutos"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "60 minutos"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "3 horas"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "6 horas"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "24 horas"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Plantilla"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tlpage_3), _translate("MainWindow", "Análisis QTVI"))
        self.groupBox_14.setTitle(_translate("MainWindow", "QTc"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Bazett"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Hodges"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Fridericia"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Rautaharju"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Framingham"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Interpolación"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Ponderación lineal"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Ponderación exponencial"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Modelo de regresión"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Lineal"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Hiperbólico"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Parabólico-Log"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Logarítmico"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Logarítmico desplazado"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Exponencial"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Arco tangente"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Arco tangente hiperbólica"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "Arco seno hiperbólico"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "Arco coseno hiperbólico"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tlpage_4), _translate("MainWindow", "Análisis QTRR"))
        self.pushButton_8.setText(_translate("MainWindow", "Pocesar Señal"))
        self.pushButton_9.setText(_translate("MainWindow", "Análisis HRV"))
        self.pushButton_12.setText(_translate("MainWindow", "Análisis QT"))
        self.pushButton_11.setText(_translate("MainWindow", "Regla"))
        self.pushButton_10.setText(_translate("MainWindow", "Escala V/H"))
        self.pushButton.setText(_translate("MainWindow", "Rejilla"))
        self.gBox_lost_beat.setTitle(_translate("MainWindow", "Latidos Perdidos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plot), _translate("MainWindow", "Registro"))
        self.groupBox.setTitle(_translate("MainWindow", "Análisis espacial HRV"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Análisis frecuencial"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Análisis no lineal"))
        self.groupBox_4.setTitle(_translate("MainWindow", "HRV Resumen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hrv), _translate("MainWindow", "HRV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_qtvi), _translate("MainWindow", "QTVI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_qtrr), _translate("MainWindow", "QTRR"))
        self.lb_name.setText(_translate("MainWindow", "Nombre(s):"))
        self.lb_ci_3.setText(_translate("MainWindow", "Edad:"))
        self.rb_m.setText(_translate("MainWindow", "Masculino"))
        self.pbt_update.setText(_translate("MainWindow", "Actualizar"))
        self.rb_f.setText(_translate("MainWindow", "Femenino"))
        self.lb_sname.setText(_translate("MainWindow", "Segundo Apellido:"))
        self.lb_fname.setText(_translate("MainWindow", "Primer Apellido:"))
        self.lb_id_clinic.setText(_translate("MainWindow", "# Historia Clínica:"))
        self.lb_id.setText(_translate("MainWindow", "Carnet de Identidad"))
        self.lb_ci_4.setText(_translate("MainWindow", "Sexo:"))
        self.lb_addr.setText(_translate("MainWindow", "Dirección:"))
        self.label_3.setText(_translate("MainWindow", "Fecha de nacimiento"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_metad),
                                  _translate("MainWindow", "Datos del Paciente"))
        self.lsw_com.setSortingEnabled(True)
        self.btn_com_add.setText(_translate("MainWindow", "Agregar"))
        self.gb_comm_pg1.setTitle(_translate("MainWindow", "Diagnóstico"))
        self.gb_comm_pg2.setTitle(_translate("MainWindow", "Tratamiento"))
        self.gb_comm_pg3.setTitle(_translate("MainWindow", "Observaciones"))
        self.btn_com_remove.setText(_translate("MainWindow", "Eliminar"))
        self.btn_com_info.setText(_translate("MainWindow", "Información"))
        self.cmbox_comments.setItemText(0, _translate("MainWindow", "Diagnóstico"))
        self.cmbox_comments.setItemText(1, _translate("MainWindow", "Tratamiento"))
        self.cmbox_comments.setItemText(2, _translate("MainWindow", "Observaciones"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_notes), _translate("MainWindow", "Estudios"))
        self.open_study.setText(_translate("MainWindow", "Abrir"))
        self.save_study.setText(_translate("MainWindow", "Guardar"))
        self.new_study.setText(_translate("MainWindow", "Nuevo"))
        self.importbtn.setText(_translate("MainWindow", "Importar"))
        self.exportbtn.setText(_translate("MainWindow", "Exportar"))
        self.confbtn.setText(_translate("MainWindow", "..."))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuVista.setTitle(_translate("MainWindow", "Vista"))
        self.menuConfiguracion.setTitle(_translate("MainWindow", "Configuración"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.action_open_study.setText(_translate("MainWindow", "Abrir"))
        self.action_new_study.setText(_translate("MainWindow", "Nuevo"))
        self.action_save_study.setText(_translate("MainWindow", "Guardar"))
        self.action_import_record.setText(_translate("MainWindow", "Importar"))
        self.action_export_record.setText(_translate("MainWindow", "Exportar"))
        self.action_Exit.setText(_translate("MainWindow", "Salir"))
        self.action_general_config.setText(_translate("MainWindow", "General"))
        self.action_user_guide.setText(_translate("MainWindow", "Guia de uso"))
        self.action_user_manual.setText(_translate("MainWindow", "Manual de usuario"))
        self.action_About.setText(_translate("MainWindow", "Acerca de"))
        self.action_toolbox_view.setText(_translate("MainWindow", "Panel de herramientas"))
        self.action_lostbeat_view.setText(_translate("MainWindow", "Panel de busqueda"))


from pyqtgraph import GraphicsLayoutWidget, PlotWidget
# import resc_rc
