# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windp.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 566)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/mono-font-awesome/images/icons/mono-font-awesome/png/open-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/mono-font-awesome/images/icons/mono-font-awesome/png/save-file-option.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/mono-font-awesome/images/icons/mono-font-awesome/png/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/mono-arrows/images/icons/mono-arrows/png/068-import-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/mono-arrows/images/icons/mono-arrows/png/071-export-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/color-sett/images/icons/color-sett/png/001-wrench-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/color-sett/images/icons/color-sett/png/025-setting-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon6)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/color-login/images/icons/color-login/png/014-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 0))
        self.toolBox.setObjectName("toolBox")
        self.tlpage_1 = QtWidgets.QWidget()
        self.tlpage_1.setGeometry(QtCore.QRect(0, 0, 200, 365))
        self.tlpage_1.setObjectName("tlpage_1")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tlpage_1)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.scrollArea = QtWidgets.QScrollArea(self.tlpage_1)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 182, 347))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout.addWidget(self.groupBox_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_21.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.toolBox.addItem(self.tlpage_1, "")
        self.tlpage_2 = QtWidgets.QWidget()
        self.tlpage_2.setGeometry(QtCore.QRect(0, 0, 200, 365))
        self.tlpage_2.setObjectName("tlpage_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tlpage_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tlpage_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.tlpage_2)
        self.comboBox.setMinimumContentsLength(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tlpage_2)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 182, 302))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_4.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_10.setFlat(True)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_4.addWidget(self.groupBox_10)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.toolBox.addItem(self.tlpage_2, "")
        self.tlpage_3 = QtWidgets.QWidget()
        self.tlpage_3.setGeometry(QtCore.QRect(0, 0, 200, 365))
        self.tlpage_3.setObjectName("tlpage_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tlpage_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tlpage_3)
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 182, 347))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_11 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_11.setFlat(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_5.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_12.setFlat(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_5.addWidget(self.groupBox_12)
        self.groupBox_13 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_13.setFlat(True)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_5.addWidget(self.groupBox_13)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.addWidget(self.scrollArea_3)
        self.toolBox.addItem(self.tlpage_3, "")
        self.tlpage_4 = QtWidgets.QWidget()
        self.tlpage_4.setGeometry(QtCore.QRect(0, 0, 200, 365))
        self.tlpage_4.setObjectName("tlpage_4")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.tlpage_4)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tlpage_4)
        self.scrollArea_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 182, 347))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_14 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_14.setFlat(True)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_6.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_15.setFlat(True)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_6.addWidget(self.groupBox_15)
        self.groupBox_16 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_16.setFlat(True)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_6.addWidget(self.groupBox_16)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_22.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.toolBox.addItem(self.tlpage_4, "")
        self.horizontalLayout.addWidget(self.toolBox)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_17.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_17.sizePolicy().hasHeightForWidth())
        self.groupBox_17.setSizePolicy(sizePolicy)
        self.groupBox_17.setMaximumSize(QtCore.QSize(160, 16777215))
        self.groupBox_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_17.setFlat(True)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_17)
        self.listWidget_2.setEnabled(False)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_23.addWidget(self.listWidget_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_17, 0, 1, 2, 1)
        self.graphicsView_1 = GraphicsLayoutWidget(self.tab)
        self.graphicsView_1.setMinimumSize(QtCore.QSize(0, 40))
        self.graphicsView_1.setMouseTracking(True)
        self.graphicsView_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.graphicsView_1.setObjectName("graphicsView_1")
        self.gridLayout.addWidget(self.graphicsView_1, 1, 0, 1, 1)
        self.graphicsView = GraphicsLayoutWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 40))
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setMinimumSize(QtCore.QSize(0, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_3.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(2)
        self.stackedWidget.setMidLineWidth(23)
        self.stackedWidget.setObjectName("stackedWidget")
        self.spage_1 = QtWidgets.QWidget()
        self.spage_1.setObjectName("spage_1")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.spage_1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox = QtWidgets.QGroupBox(self.spage_1)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.graphicsView_2 = GraphicsLayoutWidget(self.groupBox)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_20.addWidget(self.graphicsView_2, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.spage_1)
        self.spage_2 = QtWidgets.QWidget()
        self.spage_2.setObjectName("spage_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.spage_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_2 = QtWidgets.QGroupBox(self.spage_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.graphicsView_3 = GraphicsLayoutWidget(self.groupBox_2)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayout_19.addWidget(self.graphicsView_3, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.spage_2)
        self.spage_3 = QtWidgets.QWidget()
        self.spage_3.setObjectName("spage_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.spage_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_3 = QtWidgets.QGroupBox(self.spage_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.graphicsView_4 = GraphicsLayoutWidget(self.groupBox_3)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout_18.addWidget(self.graphicsView_4, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.spage_3)
        self.spage_4 = QtWidgets.QWidget()
        self.spage_4.setObjectName("spage_4")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.spage_4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox_4 = QtWidgets.QGroupBox(self.spage_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_17.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.spage_4)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.graphicsView_5 = PlotWidget(self.tab_3)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.gridLayout_4.addWidget(self.graphicsView_5, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.graphicsView_6 = PlotWidget(self.tab_4)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.gridLayout_5.addWidget(self.graphicsView_6, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_12.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setEnabled(False)
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textEdit = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_7.addWidget(self.textEdit, 0, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.tab_6)
        self.listWidget.setEnabled(False)
        self.listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_7.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuVista = QtWidgets.QMenu(self.menubar)
        self.menuVista.setObjectName("menuVista")
        self.menuConfiguracion = QtWidgets.QMenu(self.menubar)
        self.menuConfiguracion.setObjectName("menuConfiguracion")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionNuevo = QtWidgets.QAction(MainWindow)
        self.actionNuevo.setObjectName("actionNuevo")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionImportar = QtWidgets.QAction(MainWindow)
        self.actionImportar.setObjectName("actionImportar")
        self.actionExportar = QtWidgets.QAction(MainWindow)
        self.actionExportar.setObjectName("actionExportar")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionConfigurar_General = QtWidgets.QAction(MainWindow)
        self.actionConfigurar_General.setObjectName("actionConfigurar_General")
        self.actionGuia_de_uso = QtWidgets.QAction(MainWindow)
        self.actionGuia_de_uso.setObjectName("actionGuia_de_uso")
        self.actionManual_de_usuario = QtWidgets.QAction(MainWindow)
        self.actionManual_de_usuario.setObjectName("actionManual_de_usuario")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionBarra_de_herramientas = QtWidgets.QAction(MainWindow)
        self.actionBarra_de_herramientas.setObjectName("actionBarra_de_herramientas")
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionNuevo)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionImportar)
        self.menuArchivo.addAction(self.actionExportar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menuVista.addAction(self.actionBarra_de_herramientas)
        self.menuConfiguracion.addAction(self.actionConfigurar_General)
        self.menuAyuda.addAction(self.actionGuia_de_uso)
        self.menuAyuda.addAction(self.actionManual_de_usuario)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionAbout)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuVista.menuAction())
        self.menubar.addAction(self.menuConfiguracion.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        self.comboBox.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Abrir"))
        self.pushButton_3.setText(_translate("MainWindow", "Guardar"))
        self.pushButton_6.setText(_translate("MainWindow", "Nuevo"))
        self.pushButton_7.setText(_translate("MainWindow", "Importar"))
        self.pushButton_4.setText(_translate("MainWindow", "Exportar"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.groupBox_5.setTitle(_translate("MainWindow", "Filtro"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Detec"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Anotacion"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tlpage_1), _translate("MainWindow", "Procesamiento"))
        self.label.setText(_translate("MainWindow", "Vista HRV"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Analisis espacial HRV"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Analisis frecuencial"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Analisis no lineal"))
        self.comboBox.setItemText(3, _translate("MainWindow", "HRV Resumen"))
        self.groupBox_8.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_9.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_10.setTitle(_translate("MainWindow", "GroupBox"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tlpage_2), _translate("MainWindow", "Analisis HRV"))
        self.groupBox_11.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_12.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_13.setTitle(_translate("MainWindow", "GroupBox"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tlpage_3), _translate("MainWindow", "Analisis QTVI"))
        self.groupBox_14.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_15.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_16.setTitle(_translate("MainWindow", "GroupBox"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tlpage_4), _translate("MainWindow", "Analisis QTRR"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Latidos Perdidos"))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Registro"))
        self.groupBox.setTitle(_translate("MainWindow", "Analisis espacial HRV"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Analisis frecuencial"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Analisis no lineal"))
        self.groupBox_4.setTitle(_translate("MainWindow", "HRV Resumen"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "HRV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "QTVI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "QTRR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Hoja del Caso"))
        self.listWidget.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Comentarios"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuVista.setTitle(_translate("MainWindow", "Vista"))
        self.menuConfiguracion.setTitle(_translate("MainWindow", "Configuración"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionNuevo.setText(_translate("MainWindow", "Nuevo"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionImportar.setText(_translate("MainWindow", "Importar"))
        self.actionExportar.setText(_translate("MainWindow", "Exportar"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionConfigurar_General.setText(_translate("MainWindow", "General"))
        self.actionGuia_de_uso.setText(_translate("MainWindow", "Guia de uso"))
        self.actionManual_de_usuario.setText(_translate("MainWindow", "Manual de usuario"))
        self.actionAbout.setText(_translate("MainWindow", "Acerca de"))
        self.actionBarra_de_herramientas.setText(_translate("MainWindow", "Panel de herramientas"))

from pyqtgraph import GraphicsLayoutWidget, PlotWidget
import resc_rc
